INSERT INTO `service_types` (`id`, `type`, `description`)
VALUES
	(1, 'WHEEL_ALIGNMENT', 'Wheel Alignment'),
	(2, 'OIL_CHANGE', 'Oil Change'),
	(3, 'REGULAR_SERVICE', 'Regular Timely Service'),
	(4, 'COOLANT_CHANGE', 'Coolant Change'),
	(5, 'TYRE_PRESSURE', 'Tyre Pressure'),
	(6, 'REPLACE_OIL_FILTER', 'Replace the oil filter'),
	(7, 'REPLACE_FUEL_FILTER', 'Replace the fuel filter'),
	(8, 'ENGINE_TUNE', 'Engine Tune'),
	(9, 'REPLACE_SPARK_PLUG', 'Replace the spark plugs'),
	(10, 'REPLACE_CABIN_FILTER', 'Replace the cabin filter');


INSERT INTO `vehicle_data` (`id`, `wheel`, `make`, `type`)
VALUES
	(1, 4, 'hyundai', 'i10'),
	(2, 4, 'hyundai', 'i20'),
	(3, 4, 'hyundai', 'verna'),
	(4, 4, 'maruti', '800'),
	(5, 4, 'maruti', 'ritz'),
	(6, 4, 'maruti', 'omni'),
	(7, 2, 'bajaj', 'pulser'),
	(8, 3, 'bajaj', 'rickshaw'),
	(10, 2, 'honda', 'activa'),
	(11, 2, 'Roya Enfield', 'Bullet 350'),
	(12, 2, 'Roya Enfield', 'Bullet 500 Desert Storm'),
	(13, 4, 'toyota', 'altis'),
	(14, 4, 'toyota', 'etios'),
	(15, 4, 'toyota', 'etios liva'),
	(16, 4, 'toyota', 'fortuner'),
	(17, 4, 'toyota', 'innova'),
	(18, 4, 'toyota', 'land cruiser'),
	(19, 4, 'toyota', 'camry'),
	(20, 4, 'toyota', 'prado'),
	(21, 4, 'tata', 'nano'),
	(22, 4, 'tata', 'indigo'),
	(23, 4, 'tata', 'indica'),
	(24, 4, 'tata', 'safari'),
	(25, 4, 'tata', 'bolt'),
	(26, 4, 'tata', 'zent'),
	(27, 4, 'tata', 'tigor'),
	(28, 4, 'tata', 'hexa'),
	(29, 4, 'tata', 'tiago'),
	(30, 4, 'tata', 'nexon'),
	(31, 4, 'tata', 'sumo'),
	(32, 4, 'maruti', 'wagon r'),
	(33, 4, 'maruti', 'swift'),
	(34, 4, 'maruti', 'alto k10'),
	(35, 4, 'maruti', 'celerio'),
	(36, 4, 'maruti', 'ertiga'),
	(37, 4, 'maruti', 'eeco'),
	(38, 4, 'maruti', 'gypsy'),
	(39, 4, 'maruti', 'ignis'),
	(40, 4, 'maruti', 'baleno'),
	(41, 4, 'maruti', 'brezza'),
	(42, 4, 'maruti', 'ciaz'),
	(43, 4, 'maruti', 's cross'),
	(44, 4, 'fiat', '500'),
	(45, 4, 'fiat', 'avventura'),
	(46, 4, 'fiat', 'urban cross'),
	(47, 4, 'fiat', 'linea'),
	(48, 4, 'fiat', 'abarth'),
	(49, 4, 'fiat', 'punto'),
	(50, 4, 'honda', 'city'),
	(51, 4, 'honda', 'brio'),
	(52, 4, 'honda', 'amaze'),
	(53, 4, 'honda', 'jazz'),
	(54, 4, 'honda', 'WR-V'),
	(55, 4, 'honda', 'VR-V'),
	(56, 4, 'honda', 'CR-V'),
	(57, 4, 'honda', 'accord'),
	(58, 4, 'hyundai', 'creta'),
	(59, 4, 'hyundai', 'xcent'),
	(60, 4, 'hyundai', 'elantra'),
	(61, 4, 'hyundai', 'tucson'),
	(62, 4, 'hyundai', 'eon');
